#!/bin/bash

#LOG=/tmp/gen-linker-script.log
#echo "$0 $*" > $LOG

top_builddir="${0%gen-linker-script}/.."
ARGS=""

while [ -n "$*" ]; do
#   echo "[$ARGS]" 1>&2
    case $1 in
        -b) top_builddir="$2"; shift 2;;
        -c) #echo "  [$1] [$2]" 1>&2;
            ARGS="$ARGS -c '$2'"; shift 2;;
         *) #echo "  [$1]" 1>&2;
            ARGS="$ARGS '$1'"   ; shift 1;;
    esac
done

#echo "ARGS: [$ARGS]" 1>&2
#echo "ARGS: [$ARGS]" >> $LOG
#echo "${top_builddir}/utils/collect-symbols -g $ARGS" >> $LOG

eval "${top_builddir}/utils/collect-symbols -g $ARGS"
